export const data = {
  studies: [
    {
      filter: "Nodejs",
      id: "nodejs-mongodb",
      title: "nodeJS + mongoDB +react - 회원가입,로그인 기능",
      git: "https://github.com/hyemin12/nodejs_mongodb",
    },
    {
      filter: "Nodejs",
      id: "nodejs-mysql",
      title: "nodeJS + mysql +react - 투두앱 만들기",
      git: "https://github.com/hyemin12/typescript-todo-nodejs",
    },
    {
      filter: "ect",
      id: "codingtest",
      title: "코딩테스트공부 정리",
      url: "https://hyemin12.github.io/codingtest_",
    },
    {
      filter: "Typescript",
      id: "tsc-todo",
      title: "투두리스트",
      git: "https://github.com/hyemin12/typescript-todo-app",
      url: "https://hm-tsc-todo-app.netlify.app",
    },
    {
      filter: "React",
      id: "gomintalk",
      title: "리슨 버블 클론 코딩",
      git: "https://github.com/hyemin12/gomin-talk-app",
      url: "https://wizardly-hermann-7fecb3.netlify.app/",
    },
    {
      filter: "Vanilla JS",
      id: "moment",
      title: "크롬 앱",

      git: "https://github.com/hyemin12/vanillaJS-chrome-app",
      url: "https://hyemin12.github.io/vanillaJS-chrome-app/",
    },
    {
      filter: "React",
      id: "twitter",
      title: "트위터 클론 코딩",
      git: "https://github.com/hyemin12/react-firebase-twitter",
    },

    {
      filter: "Vanilla JS",
      id: "starbucks",
      title: "Starbucks 2017",
      git: "https://github.com/hyemin12/vanilla-starbucks-app",
      url: "https://starbucks-responsive-app-ee135b.netlify.app",
    },
    {
      filter: "Vanilla JS",
      id: "paint",
      title: "그림판",
      git: "https://github.com/hyemin12/vanillaJS-paint-app",
      url: "https://hyemin12.github.io/vanillaJS-paint-app/",
    },

    {
      filter: "Vanilla JS",
      id: "wordle",
      img: "wordle",
      title: "Wordle 게임",
      describtion: [
        "요즘 인기가 많은 단어를 맞추는 게임 wordle을 자바스크립트로만으로 구현한 프로젝트입니다. 게임방법은 단어를 입력하고, Enter 버튼을 눌러 제출하면 됩니다. 제출 시 정답 유무를 확인하고, 오답일 경우 각 타일의 색상이 변경되어 정답 단어에 얼마나 가까웠는지를 보여줍니다.",
        "유투브 코딩애플의 wordle 게임 영상을 보고 클론 코딩으로 시작한 프로젝트입니다. 여러 기능을 추가하고 싶어 코드를 작성했지만 제대로 작동하지 않아 해결방법을 찾던 도중 한 개발자가 블로그에 wordle 게임을 직접 구현한 코드를 공유한 것을 보았고, 이를 제 프로젝트에 적용시켰습니다. wordle 프로젝트를 만들며, 몰랐던 기능들과 해결방법에 대해 알 수 있어서 좋았고, 더 나은 코드를 작성하는 방법에 대해 공부 하는 시간을 가졌습니다.",
      ],
      date: "2022-03-20",
      tool: ["HTML", "CSS", "Javascript", "gh-pages"],
      features: [
        "1. 키보드를 누르면 해당 값이 칸에 입력되고, 제출 시 채점됨 ",
        "2. 밝은 모드 / 어두운 모드로 모드 선택 가능",
      ],
      git: "https://github.com/hyemin12/vanillaJS-wordle-app",
      url: "https://hyemin12.github.io/vanillaJS-wordle-app/",
      detailImg: ["wordle1", "wordle2"],
    },
    {
      filter: "Vanilla JS",
      id: "responsive1",
      img: "responsive1-1",
      title: "반응형 사이트 - readOnly",
      git: "https://github.com/hyemin12/responsive-webstie-readOnly",
      url: "https://hyemin12.github.io/responsive-webstie-readOnly/",
    },
    {
      filter: "Vanilla JS",
      id: "responsive2",
      img: "responsive2-1",
      title: "반응형 사이트 - massively",
      ect: "https://html5up.net/massively",
      git: "https://github.com/hyemin12/responsive-webstie-massively",
      url: "https://hyemin12.github.io/responsive-webstie-massively/",
    },
    {
      filter: "Vanilla JS",
      id: "responsive3",
      img: "responsive3-1",
      title: "반응형 사이트 - funny Flakes",
      ect: "https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbimORE%2FbtrE8N156Ne%2FEE9eIvq1Zd9k414O3vNH80%2Fimg.jpg",
      git: "https://github.com/hyemin12/responsive-webstie-funnyFlakes",
      url: "https://hyemin12.github.io/responsive-webstie-funnyFlakes/",
    },
    {
      filter: "Vanilla JS",
      id: "responsive4",
      img: "responsive4-1",
      title: "반응형 사이트 - forty",
      ect: "https://html5up.net/forty",
      git: "https://github.com/hyemin12/responsive-webstie-forty/",
      url: "https://hyemin12.github.io/responsive-webstie-forty/",
    },
    {
      filter: "jQuery",
      id: "stranger",
      title: "비밀의 숲2 프로모션",
      git: "https://github.com/hyemin12/web-design-portfolio/01Stranger2/",
      url: "https://hyemin12.github.io/web-design-portfolio/01Stranger2/",
    },
    {
      filter: "ect",
      id: "lottecard",
      title: "롯데카드 프로모션",
      url: "https://github.com/hyemin12/react-dashboard-app2/blob/master/public/img/portfolio/lottecard2.jpg?raw=true",
    },
    {
      filter: "ect",
      id: "travel",
      title: "여행사 프로모션",
      url: "https://github.com/hyemin12/react-dashboard-app2/blob/master/public/img/portfolio/travel2.jpg?raw=true",
    },
  ],
  works: [
    {
      filter: "React",
      id: "movie",
      title: "영화검색사이트",
      describtion: [
        "imdb api를 이용해서 인기 영화, 상영예정 영화, 평점이 높은 영화목록을 가져오고 영화 상세정보를 볼 수 있는 프로젝트입니다.",
        "무료 api를 활용하여 비동기 통신에 대하여 학습하기 위해 제작하였고, 이 프로젝트를 진행하며 open api를 이용해서 백엔드 서버에서 json 파일을 받아온 뒤 화면에 출력하는 방법에 대해 학습했습니다.",
      ],
      date: "2022-03-08",
      tools: ["REACT", "react-router-dom", "tmdb API", "Sass", "netlify"],
      features: [
        "1. 인기 영화, 상영중인 영화 등 다양한 데이터를 받아와서 페이지에 출력",
        "-서버에 정보를 요청하고 받아오는 것을 비동기로 처리(async,await)",
        "2. context API를 사용하여 검색기능 구현하기",
        "-search_context라는 hook 파일을 생성하고, 검색된 결과를 전역으로 관리하기",
        "3. 특정 id를 가진 영화 정보를 받아와서 상세정보 페이지 구현하기",
      ],
      imgs: ["moivePage.png", "movieDetail.png", "movieSearch.png"],
      git: "https://github.com/hyemin12/react-movie-app",
      url: "https://react-movie-app-1f5ff8.netlify.app/",
      bgColor: "#e9edec",
    },
    {
      filter: "Typescript",
      id: "mytravel",
      title: "여행일정앱",
      describtion: [
        "타입스크립트와 firebase로 작성된 포트폴리오 프로젝트입니다. ",
      ],

      date: "2022-08-08",
      tools: ["react", "Typescript", "firebase", "kakao-maps-api", "gh-pages"],
      features: [
        "1. Firebase의 auth를 활용한 회원가입, 로그인, 로그아웃 기능 구현",
        "- 이메일과 비밀번호를 이용해서 회원가입을 할 수 있고, google을 이용해서도 회원가입이 가능",
        "2. Firebase의 database를 활용한 데이터 관리 (상세일정 추가, 수정, 삭제 기능)",
        "3. DB에서 가져온 데이터를 filter해서 날짜 별 여행 일정을 확인할 수 있음",
        "4. 카카오 맵 api를 활용한 지도 구현",
        "- marker를 통한 동선 및 장소 확인",
        "- react 환경 변수를 활용하여 카카오맵 API KEY 숨기기",
      ],
      imgs: ["planBusan.png", "PlanHome.png", "planRegister.png"],
      git: "https://github.com/hyemin12/typescript-hyemin-app",
      url: "https://hyemin12.github.io/typescript-hyemin-app",
      bgColor: "#eae2cf",
    },
    {
      filter: "Typescript",
      id: "tsc-shop",
      title: "쇼핑몰",
      describtion: [
        "타입스크립트로 제작된 프로젝트입니다. 장바구니에 상품을 담고, 삭제할 수 있는 기능을 가지고 있습니다.",
        "새로운 훅을 이용하여 액션을 생성하는 방법을 배웠고, 조건에 따라 컴포넌트의 내용을 다르게 보여주는 방법에 대해서도 공부했습니다. 장바구니 state를 빈 배열로 설정할 경우 타입오류가 나타나는 것에 대해서는 문제해결을 하지 못하였습니다. 이부분 역시 관련해서  해결방법을 찾아 수정할 예정입니다.",
      ],
      date: "2022-09-01",
      tools: [
        "React",
        "Typescript",
        "redux toolkit",
        "React-router-dom",
        "netlify",
      ],
      features: [
        "1. 반응형 UI 구현",
        "- 화면이 작아질 경우 장바구니 위치와 콘텐츠 개수를 변경함",
        "2. store를 통해 state를 관리 하기 (장바구니에 추가, 삭제, 장바구니 비우기)",
        "- configureStore를 통해 store를 생성하고 createSlice를 통해 reducer를 생성하고 action을 정의",
        "- 아이템 플러스 버튼을 누르면 해당 action을 통해서 장바구니 state를 변경",
        "- 장바구니 버튼들을 누르면 장바구니 state들을 변경",
      ],
      imgs: ["shopWeb.png", "shopPhone.png"],
      git: "https://github.com/hyemin12/react-shop-practice-app/",
      url: "https://h-m-shop.netlify.app/",
      bgColor: "#d9e4eb",
    },

    {
      filter: "React",
      id: "dashboard",
      title: "대시보드",
      describtion: [
        "다양한 API를 통해 정보를 가져오고, 해야할 일 목록 작성, 음악 플레이 등 다양한 작업을 할 수 있는 대쉬보드 페이지와 개인 포트폴리오를 확인할 수 있는 페이지, 좌측 이름 옆 화살표를 클릭하면 프로필 확인이 가능한 프로젝트입니다.",
        "이번 프로젝트를 하며 react의 다양한 라이브러리들에 대해 알게되었고, redux store 를 활용하여 state를 주고 받는 방법에 대해 학습하게 되었습니다. 다양한 API를 사용하는 방법과 커스텀하는 방법에 대하여 공부하였습니다.",
      ],
      date: "2022-03-20",
      tools: [
        "React",
        "react-router-dom",
        "redux",
        "axios",
        "react-h5-audio-player",
        "@fullcalendar/react",
        "open weather api",
        "Corona-19-API",
        "netlify",
      ],
      features: [
        "1. widget을 통한 정보 확인 (현재시간, d-day, 날씨, 북마크, 코로나 19, 명언)",
        "2. 투두리스트와 캘린더를 통해 스케줄 확인 및 정리 가능",
        "3. 개인 작업물 목록과 상세 내용 확인 가능(현재는 종료됨)",
        "4. 좌측 이름 옆 화살표 클릭시 프로필 확인 가능",
      ],
      imgs: ["dashboardHome.png", "dashboardCal.png", "dashboardAbout.png"],
      git: "https://github.com/hyemin12/react-dashboard-app2",
      url: "https://lucid-yonath-d614bb.netlify.app/",
      bgColor: "#f3e7e9",
    },
  ],
  interview: [
    {
      title: "언제부터 지금의 직무에 관심을 갖게 되었나요?",
      text: "웹디자이너 · 웹퍼블리셔 과정을 수료하면서 저는 디자인 보다는 코드를 작성해서 웹을 구현하는 것에 더 큰 매력을 느꼈습니다. 다양한 기능을 구현하고 싶어 자바스크립트에 대하여 공부를 하면서 프론트엔드의 개발에 대해 알게 되었고, 하드코딩이 아닌 백엔드의 데이터로 화면을 구성하고 기능을 동작하도록 만드는 프론트엔드 개발에 관심을 가지게 되었습니다.",
    },
    {
      title: "학원을 다니지 않고, 혼자서 개발 공부를 한 이유가 있나요?",
      text: "저 역시 웹 디자인 및 웹 퍼블리셔 과정은 학원을 다니며 공부를 했습니다. 학원을 다니며, 강의를 열심히 들어도 혼자 복습하거나 꾸준히 연습하지 않으면 제 것으로 만들기 어렵다는 것을 느꼈습니다. 그래서 개발 공부할 때에는 강의를 듣고, 그 강의를 복습하는 방식으로 공부를 했습니다.",
    },
    {
      title:
        "Github commit 기록을 보면 2021년 11월부터 2022년 1월까지 commit이 안되어 있던데 무슨 일이 있었나요?",
      text: "정보처리기능사 자격증을 취득하기 위해 공부를 했습니다. 2021년 프론트엔드 강의를 듣고 개인 프로젝트를 제작하려고 하였으나, 강사의 코드를 그대로 따라 치기식으로 공부한 결과 혼자서 코드를 작성하는데 어려움을 느꼈습니다. 따라 무작정 강의를 듣는 것이 아닌 기초부터 차근차근 공부하고자 하였습니다. 컴퓨터공학의 기초 지식을 쌓을 수 있는 정보처리 기능사를 9월부터 12월까지 공부했으며 자격증 취득하였습니다.",
    },
  ],
};
